fixes:
  - "NeXus-Streamer/::"

comment:
  layout: "header, diff, tree, changes, sunburst"
  require_changes: no
coverage:
  status:
    patch: off
    project:
      default:
        target: auto
        threshold: 5
