version: '2'

services:
  producer:
    network_mode: host
    build: .
    depends_on:
      - kafka
    environment:
      CONFIG_FILE: "/example_config.ini"
      KAFKA_BROKER: "localhost"
    volumes:
      - ./docker/example_config.ini:/example_config.ini

  kafka:
    image: wurstmeister/kafka:0.11.0.1
    depends_on:
      - zookeeper
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 10000000
      KAFKA_BROKER_ID: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: zookeeper:3.4
    ports:
      - '2181:2181'
